### ISSUE TITLE
Buttons not working correctly

### ISSUE THREAD

**Issue by Ereshkigal01** [TheTerminalCafe/hugo-ttc-source#2]
Next and previous buttons are not working correctly in the website. In tutorial section upon clicking on the button its looping though the entire /tutorials/  not just the particular coerce.

--- Proposed collusion [ May differ from final code ]
  1. Remove multi paging for individual coerces , make them 1 monolithic page and add table of contents on the right.
  2. Fix the button so it only goes through immediate parent.

**Comment by Ereshkigal01** [comment]
Upon Further testing its discovered that pages are also not ordered correctly in side tutorials and buttons redirection is completely broken

**Comment by kilea-chan** [comment]
Resolved by #5
